name: ⚡️ Code Stats

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Process Stats
    runs-on: ubuntu-latest
    steps:
      - uses: dgrebb/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: Lanuages This Week
          TIME_RANGE: last_7_days
          IGNORED_LANGUAGES: YAML JSON TOML
          COMMIT_MESSAGE: "chore(readme): update codestats"
          TARGET_BRANCH: main
          COMMITTER_NAME: "@grebbops"
